CUDA_VISIBLE_DEVICES=0,1  python -m torch.distributed.launch --nproc_per_node=2 --master_port=12233 --use_env run_train.py \
--diff_steps 2000 \
--lr 0.0001 \
--learning_steps 30000 \
--save_interval 10000 \
--seed 102 \
--noise_schedule sqrt \
--hidden_dim 128 \
--microbatch 8 \
--bsz 512 \
--dataset qqp \
--data_dir datasets/QQP \
--vocab bert \
--seq_len 128 \
--schedule_sampler lossaware \
--ecc_mode true \
--ecc_num_aux_copies 1 \
--notes qqp
